//ff:func feature=scan type=model topic=laravel
//ff:what Laravel HTTP 메서드명 상수 및 apiResource CRUD 매핑
package laravel

// httpMethods maps lowercase Laravel Route method names to uppercase HTTP methods.
var httpMethods = map[string]string{
	"get":     "GET",
	"post":    "POST",
	"put":     "PUT",
	"patch":   "PATCH",
	"delete":  "DELETE",
	"options": "OPTIONS",
	"any":     "ANY",
}

// apiResourceActions defines the 5 CRUD routes generated by Route::apiResource.
var apiResourceActions = []apiResourceAction{
	{method: "GET", suffix: "", action: "index", hasParam: false},
	{method: "POST", suffix: "", action: "store", hasParam: false},
	{method: "GET", suffix: "/{%s}", action: "show", hasParam: true},
	{method: "PUT", suffix: "/{%s}", action: "update", hasParam: true},
	{method: "PATCH", suffix: "/{%s}", action: "update", hasParam: true},
	{method: "DELETE", suffix: "/{%s}", action: "destroy", hasParam: true},
}

// skipDirs are directory names to skip when walking PHP files.
var skipDirs = map[string]bool{
	"vendor":    true,
	"storage":   true,
	"bootstrap": true,
	".git":      true,
	"node_modules": true,
	"public":    true,
	".idea":     true,
	".vscode":   true,
}

// laravelValidationTypeMap maps Laravel validation rule names to OpenAPI types.
var laravelValidationTypeMap = map[string]string{
	"string":  "string",
	"integer": "integer",
	"int":     "integer",
	"numeric": "number",
	"boolean": "boolean",
	"bool":    "boolean",
	"array":   "array",
}

// laravelValidationFormatMap maps Laravel validation rule names to OpenAPI formats.
var laravelValidationFormatMap = map[string]string{
	"email": "email",
	"url":   "uri",
	"uuid":  "uuid",
	"date":  "date",
	"file":  "binary",
	"image": "binary",
}

// httpStatusConstants maps Symfony/Laravel Response::HTTP_* constant names to status codes.
var httpStatusConstants = map[string]string{
	"HTTP_OK":                    "200",
	"HTTP_CREATED":               "201",
	"HTTP_ACCEPTED":              "202",
	"HTTP_NO_CONTENT":            "204",
	"HTTP_MOVED_PERMANENTLY":     "301",
	"HTTP_FOUND":                 "302",
	"HTTP_NOT_MODIFIED":          "304",
	"HTTP_BAD_REQUEST":           "400",
	"HTTP_UNAUTHORIZED":          "401",
	"HTTP_FORBIDDEN":             "403",
	"HTTP_NOT_FOUND":             "404",
	"HTTP_METHOD_NOT_ALLOWED":    "405",
	"HTTP_CONFLICT":              "409",
	"HTTP_UNPROCESSABLE_ENTITY":  "422",
	"HTTP_TOO_MANY_REQUESTS":     "429",
	"HTTP_INTERNAL_SERVER_ERROR": "500",
}

// abortFunctions maps Laravel abort helper names to the argument index holding the status code.
var abortFunctions = map[string]int{
	"abort":        0,
	"abort_if":     1,
	"abort_unless": 1,
}
