//ff:func feature=scan type=model topic=laravel
//ff:what Laravel HTTP 메서드명 상수 및 apiResource CRUD 매핑
package laravel

// httpMethods maps lowercase Laravel Route method names to uppercase HTTP methods.
var httpMethods = map[string]string{
	"get":     "GET",
	"post":    "POST",
	"put":     "PUT",
	"patch":   "PATCH",
	"delete":  "DELETE",
	"options": "OPTIONS",
	"any":     "ANY",
}

// apiResourceActions defines the 5 CRUD routes generated by Route::apiResource.
var apiResourceActions = []apiResourceAction{
	{method: "GET", suffix: "", action: "index", hasParam: false},
	{method: "POST", suffix: "", action: "store", hasParam: false},
	{method: "GET", suffix: "/{%s}", action: "show", hasParam: true},
	{method: "PUT", suffix: "/{%s}", action: "update", hasParam: true},
	{method: "PATCH", suffix: "/{%s}", action: "update", hasParam: true},
	{method: "DELETE", suffix: "/{%s}", action: "destroy", hasParam: true},
}

// skipDirs are directory names to skip when walking PHP files.
var skipDirs = map[string]bool{
	"vendor":    true,
	"storage":   true,
	"bootstrap": true,
	".git":      true,
	"node_modules": true,
	"public":    true,
	".idea":     true,
	".vscode":   true,
}

// laravelValidationTypeMap maps Laravel validation rule names to OpenAPI types.
var laravelValidationTypeMap = map[string]string{
	"string":  "string",
	"integer": "integer",
	"int":     "integer",
	"numeric": "number",
	"boolean": "boolean",
	"bool":    "boolean",
	"array":   "array",
}

// laravelValidationFormatMap maps Laravel validation rule names to OpenAPI formats.
var laravelValidationFormatMap = map[string]string{
	"email": "email",
	"url":   "uri",
	"uuid":  "uuid",
	"date":  "date",
	"file":  "binary",
	"image": "binary",
}
